### ISSUE TITLE
Error: is not a requirement issue or is not a valid issue key

### ISSUE THREAD

**Issue by InduKrish** [Xray-App/xray-junit-extensions#28]
Not sure why xray throws an error, the requirement do exist in JIRA, but seeing the following error, Can you please explain the root cause? i submitted the xml produced by Xray plugin and used the following URI.

https://jira-tools.swacorp.com/rest/raven/1.0/import/execution/junit?projectKey=AAAA&testPlanKey=BDXP-1431&fixVersion=BDXP 2023.1.1 Release  IN-POD Testing

{
    "error": " BACW-383 is not a requirement issue or is not a valid issue key.; BACW-264 is not a requirement issue or is not a valid issue key.; BACW-353 is not a requirement issue or is not a valid issue key.; BACW-281 is not a requirement issue or is not a valid issue key.; BACW-407 is not a requirement issue or is not a valid issue key.; BACW-338 is not a requirement issue or is not a valid issue key.; BACW-112 is not a requirement issue or is not a valid issue key.; BACW-277 is not a requirement issue or is not a valid issue key.; BACW-383 is not a requirement issue or is not a valid issue key.; BACW-264 is not a requirement issue or is not a valid issue key.; BACW-353 is not a requirement issue or is not a valid issue key.; BACW-281 is not a requirement issue or is not a valid issue key.;
}

**Comment by bitcoder** [comment]
This is more a Xray related question so I'll close this ticket (these kind of doubts should be handled through [Xray support](https://jira.getxray.app/servicedesk/customer/portal/2)); nevertheless, I can tell that in advance that this may be happening because those issues are not "requirement issues". For that, you need to check with your Jira or project administrator if those issues are properly  configured to be handled as "requirements" (i.e. issues, i.e. issue types to be more precise, that can be covered with Tests) and if you have requirement coverage enabled on the project BACW; more info at https://docs.getxray.app/display/XRAY/Quick+Setup#QuickSetup-ConfigureRequirementsandDefects


Re
