### ISSUE TITLE
Assertion result not shown in Xray when uploading evidence

### ISSUE THREAD

**Issue by ncariss** [Xray-App/xray-junit-extensions#9]
I am currently doing some JUnit tests that compare very long Maps and Lists using custom Hamcrest matchers.
The matchers describe the mismatch in detail once an assertion fails. If I use the Xray-JUnit-Extension to upload the results to Jira, we can see the description of the AssertionError in the TestRun of our Testcases (test type "generic").

If, however, I also add some files as TestRun evidence, all I see in the TestRun in Jira is the link to one of the files.
Is this something that could potentially be fixed/changed in the extension or is this due to behaviour of Xray itself?

**Comment by bitcoder** [comment]
Hi @ncariss ,
to be able to help you out,

1. can you please provide more details, including a code snippet where you attach the files as testrun evidence?
2. can you provide a screenshot of the test run details you see in Xray?
3. can you provide the junit.xml file that was generated by this extension?
4. are you using Xray server/datacenter (i.e., on Jira server/datacenter) or Xray cloud (i.e., on Jira cloud)?

**Comment by ncariss** [comment]
Hi @bitcoder !
Thanks for the quick reply!

We are using Xray Server+DC.

I created a minimum working example [here](https://github.com/DevOps-Testing/junit-xray).
(Interestingly, mvn test does not find any tests, but running the tests using IntelliJ works. Apparently just including the xray-junit-extensions as a Maven dependency blocks Maven Surefire from finding any tests.)

The XML report and screenshots can also be found in the repo:
[TEST-junit-jupiter.xml](https://github.com/DevOps-Testing/junit-xray/blob/main/reports/TEST-junit-jupiter.xml)
Without evidence uploaded we can see the AssertionError (which is what we want):
![noEvidenceUploaded](https://user-images.githubusercontent.com/7630212/157548105-e96efce4-709f-448c-91d6-da8dc8a56072.png)

When uploading evidence, the AssertionError is unfortunately replaced by the evidence filename/link:
![withEvidenceUploaded](https://user-images.githubusercontent.com/7630212/157548350-68f49b94-6128-4c2e-b7be-782e7806852e.png)

Cheers
Nick

**Comment by bitcoder** [comment]
Hi @ncariss ,
so it's a bug on Xray server/DC side. I've used your report and upload to a Xray cloud instance and it shows fine as you can see. Please reach out to [Xray support team](https://jira.getxray.app/servicedesk/customer/portal/2) and report it (please provide the junit xml file you generate). You can say that the same file seems to work fine in Xray cloud as I've checked it.
I'll close this issue here. Thanks for the feedback :) 

Note: concerning `mvn test`, not sure what is happening. I can't replicate it. Besides the [workflows](https://github.com/Xray-App/xray-junit-extensions/actions/workflows/CI.yml) are running fine,

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/553801/157644090-21539b35-7c47-4d00-ac6f-ae1b73a73d57.png">

**Comment by ncariss** [comment]
Hi Sergio!
Thank you for the analysis! I will address this with the Xray support then.
Regarding the Maven issues I am facing, I will ask some colleagues to try my repo and report back in another ticket, if I can pinpoint it to the extension.
